---
vidzou_image_version: 1591063193
vidzou_image_tag: "mattjmcnaughton/vidzou:{{ vidzou_image_version }}"
vidzou_port: 8080
vidzou_port_mappings:
  - "{{ vidzou_port }}:{{ vidzou_port }}"
vidzou_volume_mappings:
  - /tmp:/tmp
  - /var/run/docker.sock:/var/run/docker.sock
vidzou_yaml_file: /tmp/vidzou.yaml
