---
- name: Perform ufw actions as root
  block:
    - name: Install ufw
      apt:
        name: ufw
        state: present

    - name: Turn on ufw
      ufw:
        state: enabled

    - name: Turn on ufw logging
      ufw:
        logging: 'on'

    # Denying inbound traffic won't impact already accepted connections (i.e. we
    # don't need to worry about this negatively impacting the ssh connection
    # we're already connected).
    - name: Deny all inbound traffic by default
      ufw:
        default: deny
        direction: incoming

    - name: Allow all outbound traffic by default
      ufw:
        default: allow
        direction: outgoing

    - name: Allow incoming traffic on specified ports
      ufw:
        rule: allow
        port: "{{ item }}"
      loop: "{{ ufw_incoming_ports_to_allow }}"

    - name: Deny incoming traffic on specified ports
      ufw:
        rule: deny
        port: "{{ item }}"
      loop: "{{ ufw_incoming_ports_to_deny }}"

    # TODO: I'm not confident these settings are persisting across reboots...
    - name: Update sysctl martian settings to prevent DOS
      sysctl:
        name: "{{ item }}"
        value: "1"
        sysctl_set: yes
        state: present
        reload: yes
        ignoreerrors: yes
      loop:
        - "net.ipv4.conf.all.log_martians"
        - "net.ipv4.conf.default.log_martians"
  become: yes
