---
- name: Remove unneeded packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages: "{{ bastion_packages_to_remove }}"
  register: result
  retries: 5
  delay: 60
  until: result is succeeded
  become: yes
