---
- name: Install docker via our docker role
  include_role:
    name: mattjmcnaughton.docker

- name: Install nginx via our nginx role
  include_role:
    name: mattjmcnaughton.nginx
  vars:
    # TODO: configure nginx
    nginx_vhost_auth_basic: true
    nginx_vhost_extra_misc_config: ""
    nginx_vhost_location_config: ""

- name: Get docker group id
  shell: |
    set -o pipefail
    getent group docker | cut -d: -f3
  args:
    executable: /bin/bash
  register: docker_group_shell
  changed_when:
    - docker_group_shell.rc == 0

- name: Parse docker group id
  set_fact:
    docker_group_id: "{{ docker_group_shell.stdout_lines[0] }}"

- name: Run vidzou container
  docker_container:
    name: vidzou
    image: "{{ vidzou_image_tag }}"
    # Could also just load the container on the machine and not actually start
    # it (i.e. `present`) but that makes testing slightly harder.
    state: started
    restart_policy: unless-stopped
    ports: "{{ vidzou_port_mappings }}"
    volumes: "{{ vidzou_volume_mappings }}"
    groups:
      - "{{ docker_group_id }}"
    # TODO: Can use `env_file` to set environment variables and overwrite when
    # launching env specific host and then issue container restart command...
    env:
      VIDZOU_S3_BUCKET: mattjmcnaughton-test-vidzou-bucket
    # TODO: Consider the log driver
