---
- name: Install docker via our docker role
  include_role:
    name: mattjmcnaughton.docker

- name: Install nginx via our nginx role
  include_role:
    name: mattjmcnaughton.nginx
  vars:
    nginx_vhost_auth_basic: true
    nginx_vhost_auth_basic_realm: vidzou
    # Proxy requests to the go server.
    nginx_vhost_location_config: |
      location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://localhost:{{ vidzou_port }};
      }

- name: Get docker group id
  shell: |
    set -o pipefail
    getent group docker | cut -d: -f3
  args:
    executable: /bin/bash
  register: docker_group_shell
  changed_when:
    - docker_group_shell.rc == 0

- name: Parse docker group id
  set_fact:
    docker_group_id: "{{ docker_group_shell.stdout_lines[0] }}"

- name: Write .env file
  template:
    src: vidzou.env.j2
    dest: "{{ vidzou_env_file }}"
    mode: '0644'

- name: Run vidzou container
  docker_container:
    name: vidzou
    image: "{{ vidzou_image_tag }}"
    # Could also just load the container on the machine and not actually start
    # it (i.e. `present`) but that makes testing slightly harder.
    state: started
    restart_policy: unless-stopped
    ports: "{{ vidzou_port_mappings }}"
    volumes: "{{ vidzou_volume_mappings }}"
    groups:
      - "{{ docker_group_id }}"
    env_file: "{{ vidzou_env_file }}"
    # TODO: Consider the log driver
