galaxy_info:
  author: mattjmcnaughton
  description: Role for provisioning host serving go-carbon-neutral.com.
  license: Apache
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
    - name: Debian

# Depends on `mattjmcnaughton.nginx` role... but we want to control how it is
# executed so we don't specify via a `dependency` block.
#
# Does assume that the `mattjmcnaughton.docker` role has already been run.
