---
- hosts: all
  become: yes

  tasks:
    - include_role:
        name: mattjmcnaughton.entropy-generator
    - include_role:
        name: dev-sec.os-hardening
      vars:
        oss_auth_pw_max_age: 99999
        # We will manage network access ourselves in a separate role.
        ufw_manage_defaults: false
    - include_role:
        name: mattjmcnaughton.ssh-hardening-lite

    # `unattended-upgrades` comes preinstalled. While we want
    # `unattened-upgrades` installed in our final artifact, we do NOT want it in
    # the base image, because it will run (and hog the apt lock) when we boot
    # the base image to run additional playbooks and create application images.
    # It is thus the responsibility of each application image to include
    # `mattjmcnaughton.system-security-updates`.
    - name: Uninstall unattened-upgrades
      apt:
        name: unattened-upgrades
        state: absent
      when: ansible_os_family == 'Debian'
      become: yes
