---
- hosts: all
  become: yes

  tasks:
    - include_role:
        name: mattjmcnaughton.entropy-generator
    - include_role:
        name: mattjmcnaughton.system-security-updates
    - include_role:
        name: dev-sec.os-hardening
      vars:
        oss_auth_pw_max_age: 99999
        # We will manage network access ourselves in a separate role.
        ufw_manage_defaults: false
    - include_role:
        name: mattjmcnaughton.ssh-hardening-lite
