---
- hosts: all
  become: yes

  tasks:
    - name: Include os-hardening role
      include_role:
        name: dev-sec.os-hardening
      vars:
        oss_auth_pw_max_age: 99999
        # We will manage network access ourselves in a separate role.
        ufw_manage_defaults: false
